platform :ios, '13.0'
DEPLOYMENT_TARGET_IOS = '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorDevice', :path => '../../node_modules/@capacitor/device'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
  pod 'LzdevelopersLazarilloMaps', :path => '../../..'
end

target 'Demo Lazarillo SDK' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  desired_ios = Gem::Version.new(DEPLOYMENT_TARGET_IOS)
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["DEVELOPMENT_TEAM"] = "825SSA448L"
        settings = config.build_settings
        current = Gem::Version.new(settings['IPHONEOS_DEPLOYMENT_TARGET'])
        if current < desired_ios
          settings['IPHONEOS_DEPLOYMENT_TARGET'] = DEPLOYMENT_TARGET_IOS
        end
      end
    end
  end
end
